import { parseAbi } from "viem";

/** 只包含我们用到的函数、事件与错误；完整 ABI 在 contracts/out。 */
export const postsAbi = parseAbi([
  "struct Auth { address from; uint256 value; uint256 validAfter; uint256 validBefore; bytes32 nonce; bytes signature; }",
  "struct Node { uint64 parentId; uint64 rootId; uint64 authorAccountId; uint8 kind; uint40 createdAt; uint32 likes; uint32 replies; uint32 reposts; bytes32 contentHash; }",
  "function mintWithAuth(address to, bytes32 salt, Auth a) returns (uint64)",
  "function createWithAuth(uint64 accountId, uint64 parentId, uint8 kind, string excerpt, bytes32 contentHash, bytes32 salt, Auth a) returns (uint64)",
  "function likeWithAuth(uint64 accountId, uint64 nodeId, Auth a)",
  "function claimAndRedeem(uint64 accountId, uint256 amount, address to)",
  "function withdrawTreasury(address to, uint256 amount)",
  "function pending(uint64 accountId) view returns (uint256)",
  "function treasury() view returns (uint256)",
  "function nodeCount() view returns (uint64)",
  "function getNode(uint64 nodeId) view returns (Node)",
  "function liked(uint64 accountId, uint64 nodeId) view returns (bool)",
  "function stats(uint64 accountId) view returns (uint256[8])",
  "function badgeBits(uint64 accountId) view returns (uint32)",
  "function thresholds(uint8 metric) pure returns (uint256[4])",
  "function priceOf(uint8 kind) view returns (uint256)",
  "function maxExcerptBytes(uint8 tier) pure returns (uint256)",
  "function mintFee() view returns (uint256)",
  "function pricePost() view returns (uint256)",
  "function priceReply() view returns (uint256)",
  "function priceRepost() view returns (uint256)",
  "function priceLike() view returns (uint256)",
  "function treasuryBps() view returns (uint256)",
  "function maxDepth() view returns (uint8)",
  "function usdc() view returns (address)",
  "function account() view returns (address)",
  "event AccountMinted(uint64 indexed accountId, address indexed to, uint256 fee)",
  "event NodeCreated(uint64 indexed id, uint64 indexed parentId, uint64 indexed authorAccountId, uint8 kind, bytes32 contentHash, string excerpt, uint256 fee)",
  "event Liked(uint64 indexed nodeId, uint64 indexed byAccountId, uint256 fee)",
  "event Split(uint64 indexed nodeId, uint64 indexed toAccountId, uint8 depth, uint256 amount)",
  "event TreasuryAccrued(uint64 indexed nodeId, uint256 amount)",
  "event BadgeUnlocked(uint64 indexed accountId, uint8 indexed metric, uint8 tier, uint256 threshold)",
  "event Claimed(uint64 indexed accountId, uint256 amount, address to, uint256 voucherId)",
  "error BadValue()",
  "error BadNonce()",
  "error BadKind()",
  "error BadParent()",
  "error NodeNotFound()",
  "error NotAccountOwner()",
  "error ExcerptTooLong()",
  "error AlreadyLiked()",
  "error InsufficientPending()",
  "error BadSignatureLength()",
  "error TransferFailed()",
]);

export const accountAbi = parseAbi([
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function balanceOf(address owner) view returns (uint256)",
  "function tierOf(uint64 accountId) view returns (uint8)",
  "function nextId() view returns (uint64)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
]);

export const usdcAbi = parseAbi([
  "function balanceOf(address a) view returns (uint256)",
  "function name() view returns (string)",
  "function version() view returns (string)",
  "function decimals() view returns (uint8)",
  "function authorizationState(address authorizer, bytes32 nonce) view returns (bool)",
  "function mint(address to, uint256 amount)",
]);
